// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlV11JKiKfKwt_tOgFC0kdKaPO9n5pKL0',
    appId: '1:783537627006:web:bfc2e7341c4c9da6399d2f',
    messagingSenderId: '783537627006',
    projectId: 'flutterassingment',
    authDomain: 'flutterassingment.firebaseapp.com',
    storageBucket: 'flutterassingment.firebasestorage.app',
    measurementId: 'G-E7LSXDLL0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuYyO1mIZ4CrwQ06DZA_XKI9uCVN5ccHo',
    appId: '1:783537627006:android:2fd43a732217d08c399d2f',
    messagingSenderId: '783537627006',
    projectId: 'flutterassingment',
    storageBucket: 'flutterassingment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkl_Iy-IIbPTZMH8g-Cp-hC3zC0hYuHAg',
    appId: '1:783537627006:ios:ec4e891010c12edb399d2f',
    messagingSenderId: '783537627006',
    projectId: 'flutterassingment',
    storageBucket: 'flutterassingment.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssingmentTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkl_Iy-IIbPTZMH8g-Cp-hC3zC0hYuHAg',
    appId: '1:783537627006:ios:ec4e891010c12edb399d2f',
    messagingSenderId: '783537627006',
    projectId: 'flutterassingment',
    storageBucket: 'flutterassingment.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssingmentTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlV11JKiKfKwt_tOgFC0kdKaPO9n5pKL0',
    appId: '1:783537627006:web:e92cb9f28cc0d994399d2f',
    messagingSenderId: '783537627006',
    projectId: 'flutterassingment',
    authDomain: 'flutterassingment.firebaseapp.com',
    storageBucket: 'flutterassingment.firebasestorage.app',
    measurementId: 'G-XZXQC1MJ3N',
  );
}
